[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = '0.8.21'
extra_output = ["devdoc", "userdoc", "storagelayout"]
evm_version = 'istanbul'
use_literal_content = true
fs_permissions = [{ access = "read-write", path = "./" }]
memory_limit = 4143554432
gas_limit = "18446744073709551615"

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true

[rpc_endpoints]
ethereum = "https://eth.llamarpc.com"
goerli = "https://ethereum-goerli.publicnode.com"
ronin-mainnet = "https://api-partner.roninchain.com/rpc"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"
localhost = "http://localhost:8545"